### ISSUE TITLE
Dataset is missing

### ISSUE THREAD

**Issue by TheodorPatrickZ** [zeal-up/Simple-LIO-SAM#2]
Hello,

I can not open the Data you note to be providing. Do you have another link, from where I could download the Datasets?

![Screenshot from 2023-05-22 13-02-38](https://github.com/zeal-up/Simple-LIO-SAM/assets/38347406/5380123c-e08a-46c9-9a6d-80fdc7972d29)

**Comment by TheodorPatrickZ** [comment]
I went to the Original LIO-SAM and converted them to ros2 bags via this script: https://gitlab.com/ternaris/rosbags
Works well for me!

**Comment by zeal-up** [comment]
@TheodorPatrickZ I have update the dataset link. I actually did use the rosbags tool to convert dataset from ros1 to ros2!
