### ISSUE TITLE
Has this algorithm been tested with the Hesa 64-line radar?

### ISSUE THREAD

**Issue by LHZ-code** [zeal-up/Simple-LIO-SAM#3]
The problem I am facing now is that the time of each point cloud of PandarQT-64 LiDAR is not relative to the time of the first point. The time field is timestamp. The node map is correct when mapping, but there is no point cloud.

**Comment by zeal-up** [comment]
I think you should modify some code in imageProjection.cpp, which is the extry of the whole pipeline. The time field of each point is use to integrate the angle of each point. You can refer codes around [here](https://github.com/zeal-up/Simple-LIO-SAM/blob/89dafd75519a5c8c1e88187f40f3378352e0c7c5/src/imageProjection.cpp#L548)

**Comment by LHZ-code** [comment]
> 
Hello senior, I have already resolved the issue you answered earlier. However, I am currently using the Pandar64 lidar for mapping, which produces approximately 72,000 points per frame. When running in ROS2, there are problems of dropped frames or no point cloud data. Could you please advise on how to adjust its communication? Specifically, do you have knowledge about DDS and the Cyclone DDS communication protocol?

**Comment by zeal-up** [comment]
I actually have a similar problem before. The message missing problem may be the ros2 bug(I think mostly the dds middleware). I spend many time to trace this problem but got no solution. I replace the default ros2 default dds (FastDDS) to cyclone dds and the problem was partially solved.
