### ISSUE TITLE
Regarding the issue with ROS2 bag

### ISSUE THREAD

**Issue by LHZ-code** [zeal-up/Simple-LIO-SAM#4]
@zeal-up Thank you very much for providing the code. I would like to ask how you created the ROS2 bag that you provided and how you ensure that it doesn't drop frames. I am recording data from both IMU and LIDAR simultaneously in ROS2, but it seems that I am losing IMU data. Could you please advise me on how to resolve this issue? Thank you once again

**Comment by zeal-up** [comment]
I think that‘s problem of ros2! Actually, I also have been counter this data-losing problem, I solve it by change the dds implementation of ros2. You can try cyclone dds or maybe else.
