### ISSUE TITLE
rviz black screen

### ISSUE THREAD

**Issue by maltoseslope** [zeal-up/Simple-LIO-SAM#5]
I had a black screen in rviz using the default setup instruction from this repo, but I was able to resolve this by adding `--ipc=host` in the docker run command, as inspired by this post: https://github.com/ros2/rviz/issues/948

Please feel free to close this issue, this is just for other people's reference, cheers.

**Comment by zeal-up** [comment]
Thanks for your advise! Feel free to open a new issue if there is problem.
